### ISSUE TITLE
Democracy.vote note supported

### ISSUE THREAD

**Issue by streetindex** [Zondax/ledger-kusama#112]
Hello, I am trying to vote on a proposal.

LedgerLive v2.34.3
Ledger Firmware v2.0.0
Kusama App v7.9111.0

Is it an issue with batch calls? On polkadot.js I've tried connecting ledger via WebUSB as well as WebHID. I've also tried using Ledger Live's Kusama app as well as their KusamaXL app. After a couple days now trying here are the errors I've received:

Unable to claim interface
Not supported
Democracy.vote not supported

**Comment by nicolasochem** [comment]
Same here. Error from polkadot.js: ```democracy.vote
Not supported```

This is on polkadot with the polkadot XL app.

I have voted before with a ledger account, so a runtime upgrade broke it (I am not sure how recent).

**Comment by nicolasochem** [comment]
In case it's helpful to anyone: if you casted a democracy vote with ledger in the past, you'll be able to uncast it but not to call democracy/unlock: it gives a red "X" error.

To resolve, create a non-ledger governance proxy and call the unlock extrinsic with it. It works. You can then cast future democracy votes using the same proxy account.
