### ISSUE TITLE
balances.transferKeepAlive - Not Supported on Ledger

### ISSUE THREAD

**Issue by Wave3TV** [Zondax/ledger-kusama#113]
balances.transferKeepAlive
Not supported

Kusama app v7.9111.0

#104 -- The issue remains on balances.transferKeepAlive! See above. I am using v7.9111.0 and the issue persists.

**Comment by Wave3TV** [comment]
I confirmed I can send a normal transfer *without keep alive checks* 

but it's "Not Supported" when attempting to transfer *with keep alive checks*

**Comment by nespo383** [comment]
I have same issue also with the "without keep alive checks"
Ledger updated with firmware 2.0 but nothing chaged.
...It's not funny to have the founds blocked in this way!!!

**Comment by jleni** [comment]
This was submitted a few weeks ago in this PR
https://github.com/LedgerHQ/app-kusama/pull/12

Funds are not blocked, however, in the Light version it is not possible.
Until Ledger releases the update, you can install the XL version of the app that supports a wider range of tx types.
