### ISSUE TITLE
Redeem Not Supported Polkadot.js

### ISSUE THREAD

**Issue by CryptoBelieverr** [Zondax/ledger-kusama#114]
Hello,

I´m trying to redeem my ksm tokens but when I click on Sign on Ledger it shows "Not supported".

I´m using:

LedgerLive v2.34.3 (closed during transaction)
Ledger Firmware v2.0.0
Kusama App v7.9111.0

I tried also with several browsers and I don´t know what more can I do.

I will appreciate your help,

Thanks.

**Comment by CryptoBelieverr** [comment]
If anyone is experiencing the same error, I could solved it. Ksm and Dot have two apps each in Ledger, the regular one and the XL one. The problem appears with the regular app, so you need to use the XL. For Ksm it is available directly for downloading, but for Dot you need to enable Developer mode first.

**Comment by jleni** [comment]
>. The problem appears with the regular app, so you need to use the XL. 

This is actually intentional, not a problem. Many advanced features are only available in the XL version. This was requested due to Nano S space limitatation.
