### ISSUE TITLE
Generating metadata calls for a Substrate chain

### ISSUE THREAD

**Issue by jbargu** [Zondax/ledger-kusama#120]
I would like to port the app to a new substrate chain. Are the files such as https://github.com/Zondax/ledger-kusama/blob/master/app/src/substrate_dispatch_V7.c, https://github.com/Zondax/ledger-kusama/blob/master/app/src/substrate_types_V7.c auto-generated? If not, could you please provide your approach on how to systematically port metadata for an arbitrary chain?

**Comment by jleni** [comment]
This seems obsolete and out of scope. Closing
