### ISSUE TITLE
xcmPallet.limitedTeleportAssets method not supported

### ISSUE THREAD

**Issue by yanil3500** [Zondax/ledger-kusama#121]
I would like to accept RMRK tokens on Statemine but cannot because it is not possible to 'teleport' KSM over to initialize the Statemine account. Can devs do something please?

**Comment by carlosala** [comment]
Hi! We released a new version of the app `v15.9310.0` that also bundles that methods from XcmPallet.
Due to hardware limitations in the Ledger Nano S, it's only going to be available for Nano S+ and Nano X.
Thanks for the report!
