### ISSUE TITLE
Sign on Ledger does not work

### ISSUE THREAD

**Issue by z-boson** [Zondax/ledger-kusama#124]
I am using polkadot.js with my ledger and I want to teleport some KSM to Statemine chain. But when I press "Sign on Ledger", I get the error message "Not supported".

Parity Polkadot v0.9.13
api v6.11.1
apps v0.98.2-142

ledger kusama app v8.9130.0

![grafik](https://user-images.githubusercontent.com/9560482/145726801-9c0fa108-6b3d-410a-ac62-31136be1ed4e.png)
![grafik](https://user-images.githubusercontent.com/9560482/145726805-2609fb8a-7a86-4762-917f-dfa2699fe2d4.png)

**Comment by jleni** [comment]
We have already upgraded to v8.9130 and provided the changes to Ledger two weeks ago.

Reference: https://github.com/LedgerHQ/app-kusama/pull/14

have you tried upgrading your device?

**Comment by Avinash007cc** [comment]
already using v8.9130 still showing not supported.

<img width="574" alt="ksm" src="https://user-images.githubusercontent.com/96330747/147662830-81a5450e-e7a6-4565-83b2-c5c199822719.PN
<img width="932" alt="ksm2" src="https://user-images.githubusercontent.com/96330747/147662838-3eb9868c-4208-4dd7-ae82-6ea2e0604240.PNG">
G">

**Comment by Avinash007cc** [comment]
already using v8.9130 still showing not supported.

<img width="574" alt="ksm" src="https://user-images.githubusercontent.com/96330747/147662922-f0867365-87d5-488e-8328-dd25b07f7e85.PNG">
