### ISSUE TITLE
Txn version not supported-Kusama

### ISSUE THREAD

**Issue by Avinash007cc** [Zondax/ledger-kusama#128]
error:
Txn version not supported happens with every transaction.

This needs to be rectified ASAP, I need to Bond more funds

<img width="417" alt="ksm" src="https://user-images.githubusercontent.com/96330747/147379045-a690b26d-e3dd-4814-a7ee-e94aae4449bc.PNG">
<img width="841" alt="ksm2" src="https://user-images.githubusercontent.com/96330747/147379046-a1e59468-812a-49b5-8a0f-c539b8346b7e.PNG">

**Comment by jleni** [comment]
This seems obsolete and related to a missing update in Ledger Live.
