### ISSUE TITLE
Democracy extrinsics fail on 9170 with "Unexpected call index"

### ISSUE THREAD

**Issue by bjweaver** [Zondax/ledger-kusama#136]
To reproduce:

In PolkadotJS go to extrinsics/democracy/delegate and delegate votes to another account.

**Comment by bjweaver** [comment]
Also voting for council members also fails with the same error.

**Comment by jleni** [comment]
Democracy delegate is not supported.
You can check for supported methods in this list:

https://github.com/Zondax/ledger-kusama#democracy

We have created a ticket to track this https://github.com/Zondax/ledger-kusama/issues/137

**Comment by jleni** [comment]
About council.vote, this is only supported in the XL version of the app (nano S) or in the app that comes with a Nano X. 

You can check support for this here:
https://github.com/Zondax/ledger-kusama#council
