### ISSUE TITLE
Txn version not supported - Kusama

### ISSUE THREAD

**Issue by nbarrocas** [Zondax/ledger-kusama#139]
Hi! 
Can someone help? Was trying to send token from ledger wallet to another one.

Ledger Nano X
Firmware is up to date: 2.0.2

Kusama (KSM)
Version 9.9160.1 • 128 KB

Thanks!

**Comment by nbarrocas** [comment]
<img width="580" alt="Screenshot 2022-03-12 at 21 27 55" src="https://user-images.githubusercontent.com/1453456/158033954-9b5dff4c-766e-4e11-8e2b-26b76b147832.png">

**Comment by jleni** [comment]
Kusama is already running v10.9170

<img width="191" alt="image" src="https://user-images.githubusercontent.com/13698520/158035537-0c88bb19-a130-49db-baea-8f170b771aa7.png">

you can see that our changes were already accepted by Ledger 11 days ago
