### ISSUE TITLE
democracy vote not supported

### ISSUE THREAD

**Issue by everalesson** [Zondax/ledger-kusama#146]
Good evening,

I've tried voting on democracy (Ledger Nano X, firmware version 2.0.2, Kusama Version 11.9180.1 ) and it fails due to "Unexpected call index" although it says in your documentation that it is supported. Is this a known issue?

Regards,
ever

**Comment by ftheirs** [comment]
Hi @everalesson! Could you provide more info? Some snapshot would be nice! I checked that democracy pallet is indeed supported but you are getting a message that means that it's not.
Besides, there was a change in tx version and the last app version supports both (tx version 10 and 11). However, democracy pallet was added to tx version 11. Could you tell me which version were you using? If you try now, it should work.

**Comment by everalesson** [comment]
Hi @ftheirs! Just tried again today and same result, I'm not sure what are you asking about the version but the version of the Kusama app installed in my ledger is 11.9180.1. 

Attached you can find a snapshot of the input and the error:
![Screenshot 2022-04-22 at 18 35 33](https://user-images.githubusercontent.com/60576278/164757200-ea8f6fe9-9096-4907-8497-7723141f31cb.png)

Let me know if you need anything else.

**Comment by carlosala** [comment]
Hi! I was revising the repo and looks like the democracy pallet has been added in version `11.9180.2`, exactly in [this](https://github.com/Zondax/ledger-kusama/commit/a642a2e915247a85a953f74f8e5974426e357f0f) commit.
It looks like updating the app will solve it!
I'll close this, feel free to reopen if doesn't work!

**Comment by everalesson** [comment]
Update is not available, do you know when that patch will be released?

**Comment by carlosala** [comment]
Hmm, I just installed in my nanoS+ the `11.9180.3`.
Maybe Ledger has not released yet the app in nanoX. We (zondax) don't control when the app is released in the official Ledger Live market, they have to check the apps and some sort of processes that may take some time. Sorry about that :(
Have a nice week!

**Comment by everalesson** [comment]
Okay, thank you for your help!!
