### ISSUE TITLE
Latest version unavailable on Ledger live

### ISSUE THREAD

**Issue by alko89** [Zondax/ledger-kusama#163]
I noticed the version on here is v12.9250.0, but on Ledger live I can still only install v11.9230.0. Was the latest version not published? I'm using the latest version of Ledger Live and Ledger nano X

:link: [zboto Link](https://app.clickup.com/t/2rgumt5)

**Comment by ftheirs** [comment]
Our PR was merged 6 days ago (https://github.com/LedgerHQ/app-kusama/pull/23). I think that is a matter of time until Ledger publish the new version but I'll ask about it 🙂

**Comment by carlosala** [comment]
Hi @alko89,
Thanks for your report, we are actually aware of that. Ledger received our update some days ago, and we asked them to release it asap. It should not take a long time, sorry for the inconvinience 😉

**Comment by alko89** [comment]
Great! Thanks for the quick reply. :+1: I can wait a while longer
