### ISSUE TITLE
Txn not supported 

### ISSUE THREAD

**Issue by cryptoshepherd** [Zondax/ledger-kusama#164]
Hi All,

This issue affected a lot of user in the past and I'm wondering if it came back. It seems that 
I'm not able to trasnfer KSM from tle ledger nano x, I'm getting the error every time I'm ask to sign the Txn.

Kusama App v11.9230.0 and Polkadot js extension 0.44.1 

is only me or the issue does exists ? 

cheers

:link: [zboto Link](https://app.clickup.com/t/2t23k4a)

**Comment by muhazzz** [comment]
I have the same error while trying to make KSM transfer with latest Kusama App on Ledger Nano X.

**Comment by carlosala** [comment]
Hi! This is a duplicated of #163. Sorry for the delay, Ledger is going to release in the next days!

**Comment by cryptoshepherd** [comment]
> Hi! This is a duplicated of #163. Sorry for the delay, we expect Ledger is going to release in the next days!

Oh great. thanks man

**Comment by alko89** [comment]
I've asked on their Discord about this where I got the same answer: "next few days" which is now almost a week. I think there needs to be a stronger push to the Ledger team to release the darn thing.

We're basically stuck with our tokens, unable to make transactions, which is critical and should be handled with priority. I'm beginning to find their lack of action unacceptable.

**Comment by carlosala** [comment]
Hi @alko89,
The timeline for releases in Ledger Live is totally out of our scope. I apologize for all issues with your tokens that this delay raised to you. I hope it's going to be fixed in the following days.
As soon as we see that Ledger released in Ledger Live, we'll notify it in this issue and close it 👌🏻

**Comment by alko89** [comment]
@carlosala I understand, as I mentioned I'm not disappointed in your team, but Ledger

**Comment by carlosala** [comment]
New version released on Ledger Live! 🎉

**Comment by alko89** [comment]
Can confirm working! :tada:
