### ISSUE TITLE
Txn version not supported message when trying to send KSM

### ISSUE THREAD

**Issue by arctictea** [Zondax/ledger-kusama#169]
Hi I am getting a Txn version not supported message when I am trying to send out my ksm using my ledger nano S and the polkadot.js.org website. I tried turning off the keep alive checks thinking it might help but it still shows this message. So currently I can't send my KSM out! I even tried changing my node from Parity to Onfinality.

It worked before on the 20th of this month (sept) which was the last time I sent KSM but now it doesn't? Why?

Thanks in advance.

Current Specs:
Ledger Nano S Firmware 2.1.0 latest
Ledger Kusama app Version 12.9250.0 latest (I checked on Ledger Live)
https://polkadot.js.org/ website
Windows 10
Chrome latest version

:link: [zboto Link](https://app.clickup.com/t/308nhqq)

**Comment by carlosala** [comment]
Hi!
Ledger is currently reviewing our upgrade for the new version and should be available in a few days in Ledger Live!
Sorry for the inconvenience!

**Comment by ftheirs** [comment]
In the meantime, you could try using [our release](https://github.com/Zondax/ledger-kusama/releases/tag/v13.9290.0) but as Carlo said, the official Ledger release will be available soon 🙂

**Comment by arctictea** [comment]
> In the meantime, you could try using [our release](https://github.com/Zondax/ledger-kusama/releases/tag/v13.9290.0) but as Carlo said, the official Ledger release will be available soon 🙂

Thank you to both of you!

If I can't wait, how do I install the latest release you linked onto my Nano S? Is there a guide?

**Comment by carlosala** [comment]
I'm afraid this installers are only available for macOS and Linux, which OS are you currently using?

**Comment by arctictea** [comment]
> I'm afraid this installers are only available for macOS and Linux, which OS are you currently using?

I am on Windows 10

**Comment by arctictea** [comment]
But I have access to a Macbook

**Comment by carlosala** [comment]
Just downloading and executing the script would be enough (you probably need to install `ledgerblue` using `pip install ledgerblue`)

**Comment by carlosala** [comment]
Ledger released the new version in Ledger Live, we can close this!
Sorry for the inconvenience, and have a nice day! :)
