### ISSUE TITLE
Txs not supported

### ISSUE THREAD

**Issue by BCpowerup** [Zondax/ledger-kusama#173]
Txn version not supported, using latest chrome on OSX, firmware 2.0.2 v13.9290.0

doesn't allow me to unbond funds, in Kusama, tried everything possible connecting through chrome, and its settings.

:link: [zboto Link](https://app.clickup.com/t/33v04k7)

**Comment by ftheirs** [comment]
Hi @BCpowerup! Could you provide more details? Besides, there is a new version of the app. Could you update it and check once again?

**Comment by zoooeys** [comment]
Same issue when attempting to bond more. via Polkadot.js, transaction is halted before confirmation with a "Tx Not Supported" message. In Nova mobile wallet, it says "Metadata is outdated"

**Comment by ftheirs** [comment]
Ohhh, the last version from Kusama app is not published yet in Ledger Live and there are breaking changes in the app.
If you have a NanoS or NanoS+, you can try using the [release from this repository](https://github.com/Zondax/ledger-kusama/releases/tag/v14.9300.1) but the official release from Ledger should be published really soon

**Comment by BCpowerup** [comment]
all good, seems ledger takes its time!

thanks for all the good work!
