### ISSUE TITLE
Issue with Kusama sent from Bifrost wallet to my Ledger

### ISSUE THREAD

**Issue by Vjauser71** [Zondax/ledger-kusama#175]
Hi guys, really hope someone can help me out here. I've sent my Kusama from my Bifrost wallet directly to my Ledger Nano address showing in the Kusama substrate portal. Now they don't show up in my Ledger account. Looking at the transaction in Subscan I can see that they have been sent to a completely different address that is somehow connected to my Ledger address when I look it up on the Sub ID website. Does anyone have experience with this and know how I can access my Kusama? :-(
Thanks!

:link: [zboto Link](https://app.clickup.com/t/34xfwvn)

**Comment by carlosala** [comment]
Follow [this tutorial](https://zondax.ch/blog/recover-blocked-ksm) on Kusama app, and you should be able to recover your funds.
Feel free to reopen if this doesn't solve your issue!
Thanks for your contribution!
