### ISSUE TITLE
Support request. Nesting for staking.chill() and staking.unbond().

### ISSUE THREAD

**Issue by stepanLav** [Zondax/ledger-kusama#184]
In the [NovaWallet](https://novawallet.io/) we have almost whole support for staking features with Ledger except one case, when user want to unbond all his tokens, because for it need to sign `utility.batchAll() `operation with `staking.chill()` and `staking.unbond()` calls. 
[Example](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.polkadot.io#/extrinsics/decode/0x18020806060602025a6202)
<img width="200" alt="Screenshot 2022-12-15 at 10 18 26" src="https://user-images.githubusercontent.com/40560660/207797696-9389d276-436f-4b0a-954c-6739e024ef43.png">

Our users would be very glad to use the ledger in such scenarios. Is there any possibility that this functionality could be supported?

:link: [zboto Link](https://app.clickup.com/t/8676xyc67)

**Comment by carlosala** [comment]
This will be supported in the next app version.
Thanks for the report!
