### ISSUE TITLE
Transaction has a bad signature

### ISSUE THREAD

**Issue by CryptoBelieverr** [Zondax/ledger-kusama#185]
I´m getting this error when trying to unbond my ksm. Can´t even stop nominations. I have the ksm app updated in my ledger, have tried it in different browsers, have tried to restart everything, have tried to delete the account from polkadot.js and restore it again...and it didn´t solve.

I did some staking operations two days ago and everything was fine. I updated the ledger app today, as requested, and then this message appears.

Don´t know what more can I do, I´m always getting that same error, so I would really appreciate your help.

Thanks in advance.

:link: [zboto Link](https://app.clickup.com/t/8676y13cf)

**Comment by carlosala** [comment]
duplicated of #175

**Comment by CryptoBelieverr** [comment]
> duplicated of #175

Sorry man, how is this issue duplicated with #175?

That one is about sending ksm to dot or viceversa. This one is about a bad signature error when unstaking ksm. I don't get it.

**Comment by ftheirs** [comment]
Hey @CryptoBelieverr, bad signature errors are related to a wrong hdpath. Feel free to reopen the issue but add please some extra info cause it's hard to tell what might be wrong from the original description.

**Comment by CryptoBelieverr** [comment]
> Hey @CryptoBelieverr, bad signature errors are related to a wrong hdpath. Feel free to reopen the issue but add please some extra info cause it's hard to tell what might be wrong from the original description.

But what extra info would you need. Don't have much more. I click on the stop button to stop my nominations, I sign it on my ledger and this message appears. I'm doing exactly the same as always. I bonded some tokens two days ago and it worked and today I updated the app in the ledger and this message appears.

**Comment by carlosala** [comment]
Please follow what's indicated in the answer to that issue!
You should be good to go if using https://github.com/Zondax/ledger-kusama/issues/175#issuecomment-1347966917

**Comment by CryptoBelieverr** [comment]
> Please follow what's indicated in the answer to that issue! You should be good to go if using [#175 (comment)](https://github.com/Zondax/ledger-kusama/issues/175#issuecomment-1347966917)

What exactly I´m supposed to do? Because I don´t have the funds in other account that I need to recover, I just have the tokens staked. I tried to make the transaction with the recovery mode activated but it doesn´t solve the problem. And the rest of the tutorial is just to add the ledger account in polkadot.js and sending the tokens "lost" that now should appear to other account, but that´s not my case. So what I´m supposed to exactly do with the answer in #175?

**Comment by CryptoBelieverr** [comment]
I just tried to bond more funds and same error appears and I just did this two days ago before the updating of the app. Couldn´t it be for something related to this updating?

**Comment by carlosala** [comment]
@CryptoBelieverr let's reopen then. Please, do not be aggressive, we are trying to help you as much as we can.

Please, try to re-add the account to polkadot-js using ledger, both with normal and recovery mode. Could you tell us if one of the two is the one you are trying to use, and which one?

**Comment by CryptoBelieverr** [comment]
Aggressive?? lol, no man. Sorry if it seemed like that (maybe it´s just my English, my bad), but I promise that I wasn´t talking in a bad way, ofc not, it would be silly from me if I´m looking for help!

It´s weird, because I tried to re-add with normal and recovery mode mode and both shows different addresses to the one in which I had the funds.

**Comment by CryptoBelieverr** [comment]
Indeed, I have no idea how to add the account again using the adding ledger option, all the addresses added are different. Luckily, I have the account in the polkadot.js extension in other browser, so the only way that I find to re-add it again in the other browser from which I deleted the account is exporting a json file from the other browser´s extension and importing it on this.

**Comment by CryptoBelieverr** [comment]
Ok, I solved it. I had some hidden accounts in the ledger and I found out that I had the names in the polkadot.js extension mixed (no idea why) and was using the wrong pin in the ledger. Sorry for the inconvenience, but at least, it has been solved.

Thank you for your time.
