### ISSUE TITLE
Error "staking.chill 1010: Invalid Transaction: Transaction has a bad signature"

### ISSUE THREAD

**Issue by CryptoBelieverr** [Zondax/ledger-kusama#186]
I´m trying to unbond my ksm on polkadot.js and when I try to stop my nominations and sign the transaction on my ledger, this error message appears.

I bonded some tokens a couple of days ago and it worked fine, but today I updated the kusama app on my ledger and it started to fail.

I tried to use different browsers, to restart everything, delete and install again the app, remove the account from polkadot.js extension and import it again, use parity, OnFinalty, etc. and nothing solves the problem.

I have read that this error normally appears when there are some problems with different chains (ksm/dot) or something like that, but nothing to be to this case. I´m just trying to unbond my ksm as many other times.

Will appreciate any help, I don´t know what else can I do.

Thank you.

:link: [zboto Link](https://app.clickup.com/t/8676y453z)

**Comment by carlosala** [comment]
duplicated of #185, please continue discussion there
