### ISSUE TITLE
Ledger KSM wallet unsigned

### ISSUE THREAD

**Issue by baijunjie** [Zondax/ledger-kusama#188]
<img width="546" alt="image" src="https://user-images.githubusercontent.com/7956480/215237045-5cb98b48-5661-4109-9798-833cf7d44a17.png">

It seems that because of the recent upgrade of KSM.
Are there any upgrades planned for the ledger KSM wallet in the near future?

:link: [zboto Link](https://app.clickup.com/t/86778zj8r)

**Comment by carlosala** [comment]
Ledger is working on it, as soon as they upgrade we'll ping you in this issue!

**Comment by carlosala** [comment]
The upgrade already happened, closing! :)
