### ISSUE TITLE
Support request. Nested calls for ConvictionVoting pallet.

### ISSUE THREAD

**Issue by stepanLav** [Zondax/ledger-kusama#192]
Hello!
Our [team](https://novawallet.io/) is very happy to use the ledger application with Nova Wallet app and recently we delivered a new scope of features connected to ConvictionVoting pallet - [twitter_link](https://twitter.com/NovaWalletApp/status/1636009510656704512). To allow our Ledger users to continue to use the application, we ask for support for `nested` calls to the pallet. In order to make things work, we need nesting support for all calls from https://github.com/Zondax/ledger-kusama#convictionvoting

Some examples of our operations:
- Delegate to all tracks: [utility (batch_all)](https://kusama.subscan.io/extrinsic?module=utility&call=batch_all)
- Revoke from some tracks: [utility (batch_all)](https://kusama.subscan.io/extrinsic?module=utility&call=batch_all)

:link: [zboto Link](https://app.clickup.com/t/8677qz9qb)

**Comment by carlosala** [comment]
Added in `v9.9430.0`.
Thanks for your contribution :)
