### ISSUE TITLE
Kusama app showing up on ledger live as a binance token (BEP20)

### ISSUE THREAD

**Issue by RoryShively** [Zondax/ledger-kusama#194]
Hopefully this issue belongs here. Not sure if it is an issue with publishing, bad config, or a concern for the ledger team.

Why does the Kusama app consider KSM a BEP20 token?

Looking at polkadot (DOT) it seems to be a native token. Ive seen articles where this didn't seem to always be the case
https://guide.kusama.network/docs/kusama-ledger/

Here's some pics to show what I mean

<img width="768" alt="ledger-kusama-app_catalog" src="https://user-images.githubusercontent.com/8540445/232464169-a29609b1-e018-413e-aacf-8afab878d0e3.png">

<img width="513" alt="ledger-kusama-add_account" src="https://user-images.githubusercontent.com/8540445/232464174-d64beb31-ba30-4ec2-bcbb-bfaaba1ed912.png">

:link: [zboto Link](https://app.clickup.com/t/863ggke49)

**Comment by carlosala** [comment]
Hi! That's not an issue actually. Kusama is not supported on ledger live natively, you'll need to use polkadot.js.org/apps for it, but its BEP20 token is. Many tokens outside of BSC have also a token inside. In this case, kusama's one address is `0x2aa69E8D25C045B659787BC1f03ce47a388DB6E8`.
Have a nice week!
