### ISSUE TITLE
Txn version not supported returned yet again?

### ISSUE THREAD

**Issue by Appryhandsome** [Zondax/ledger-kusama#198]
Hi, 

I've read through https://github.com/Zondax/ledger-kusama/issues/104 & https://github.com/Zondax/ledger-kusama/issues/122 and I've been reading a ton of online posts / complaints... 

Overall people seem to claim that if one uses or commits these steps:

* Latest Ledger Firmware
* Latest version of Ledger Live
* Reinstall latests Kusama app on Ledger
* Reconnect ledger to Polkadot.js browser extension in Chrome
* Upgrade metadata of polkadot.js browser extension
* Log in on https://cloudflare-ipfs.com/ipns/kusama.dotapps.io or https://polkadot.js.org/apps/ 

Then your transactions should work.

I have done all of this, but no matter what I do, whenever I want to empty the KSM from my wallet (reap the sender) I continuously get the "Txn version not supported error".  

It makes a for a very frustrating user experience. 

Am I right to conclude there have been more changes to Kusama and the Ledger Live app isn't working anymore?
Thnx!

Edit: also regular transfers (that do not fully empty the wallet and both with and without the 'keep alive' option selected) all fail with message txn version not supported. 

I am using Ledger Live 2.58.0 (firmware version). The latest Kusama app Ledger Live offers me (20.9391.0). And a polkadot.js extension version 0.44.1 in Chrome.  

:link: [zboto Link](https://app.clickup.com/t/86781mq84)

**Comment by carlosala** [comment]
We already sent the update to Ledger, they'll apply it soon.

**Comment by carlosala** [comment]
Ledger already released, closing
