### ISSUE TITLE
Txn version not supported: Polkadot staking dashboard

### ISSUE THREAD

**Issue by rossbulat** [Zondax/ledger-kusama#201]
Is the Kusama Ledger app supporting the latest runtime? It is currently unable to sign transactions on staking dashboard.

:link: [zboto Link](https://app.clickup.com/t/861n1kd0d)

**Comment by carlosala** [comment]
hi Ross! Yeah, Ledger is taking a bit of time to update the app, but it's on their pipeline. I'll answer here once they release and you'll be able to upgrade in Ledger Live.
Sorry for the inconvenience!

**Comment by Halann** [comment]
I have the same problem, is there a date for the ledger to release the v23.9430.0 update?

**Comment by ainhoa-a** [comment]
Hi @Halann the update is expected to be released by Ledger before end of this week.

**Comment by anktababa** [comment]
Hi, 
Any update ? 
Still not possible to do any transaction/stacking. 
Just checked nothing available on ledger live.

Thanks

**Comment by longs8f** [comment]
Hey, i had same issue "Txn version not supported" on Kusama ledger app, please push up this case asap 😖

**Comment by ainhoa-a** [comment]
I'm really sorry, this is currently really in Ledger's hands. They are finishing the review and it should really be released soon.

**Comment by Sudo-Whodo** [comment]
Version 23.9430.0 was been released by Ledger.
