### ISSUE TITLE
Support for People Chain

### ISSUE THREAD

**Issue by lobis** [Zondax/ledger-kusama#212]
Recently the identity management was moved from the Kusama relay chain into a parachain (People chain). This means that for users such as myself that created an identity using ledger on the relay chain, it's now impossible to modify this identity. Currently to my knowledge it's not possible to interact with the People chain via ledger.

Will this be implemented in the near future?

Thanks,
Luis

**Comment by ftheirs** [comment]
Hey @lobis! No updates from the Kusama app are expected. On July 1st, the Polkadot generic and migration app will be released, and these apps should support most/all pallets.
