### ISSUE TITLE
UI displays addresses without network prefix

### ISSUE THREAD

**Issue by DemiMarie-parity** [Zondax/ledger-kusama#24]
This could be very confusing to users, and might very well cause them to blindly accept transactions (because they can’t do anything otherwise).

**Comment by jleni** [comment]
Related to https://github.com/Zondax/ledger-polkadot/issues/6
As we discussed, this is incorrect. addresses contain a network prefix, however, if you use a devnet, then the genesis hash will not match and a generic address will be shown.
