### ISSUE TITLE
Installation woes

### ISSUE THREAD

**Issue by dvdplm** [Zondax/ledger-kusama#42]
I ran into these two gotchas when installing the app:

- had to install the Ledger Manager desktop app and set up the ledger or the install_ledgeracio_app.sh script doesn't work
- the Ledger Manager desktop app must not run while the `install_ledgeracio_app.sh` runs

TBH I don't know if any of the above is worth fixing, but might be worth mentioning in the README?

**Comment by jleni** [comment]
In general terms, the installer is just provided for development/testing purposes. We prefer to avoid providing final user instructions until the app is officially published by Ledger and people can install it via the standard channels.

We don't expect `install_ledgeracio_app.sh` to be part of the normal installation workflow. This is only provided for QA/testing purposes.

About your comments:
- Yes, this is correct. Before installing any new app, Ledger devices have to be initialized and provisioned. You need to generate a mnemonic, write it down, etc. In some cases, you may even want to upgrade the firmware. 

- Yes, Ledger devices cannot handle two clients at the same time. This is the general case.

Having said so, I agree that we can create a small section and disclaimer explaining what I wrote here. Maybe we can discuss with @DemiMarie creating a brief document for Parity's internal use.

**Comment by dvdplm** [comment]
I think @DemiMarie is already working on such a document and I think the info above should be included in some form. Closing this for now. :)
