### ISSUE TITLE
Error: Unable to reset the device #4049

### ISSUE THREAD

**Issue by anjaw3f** [Zondax/ledger-kusama#43]
We have several users report the error "Unable to reset the device" when trying to connect their Ledgers on https://polkadot.js.org/apps/#/accounts. One person solved it by changing to the Edge browser, others have the same issue in the Edge browser, though.

I don't have a lot of data yet, but definitely notice an uptick of tickets for this particular error.

![Screenshot 2020-11-19 at 09 36 51](https://user-images.githubusercontent.com/70277946/99654450-02adb700-2a63-11eb-83be-9a4cb7e70ea4.png)

See this issue for reference: https://github.com/polkadot-js/apps/issues/4049

**Comment by douglasdeodato** [comment]
I got the same issue using: chrome Version 87.0.4280.66 (Official Build) (64-bit) , problem solved after switch to edge. I would say the problem it is in this chrome build?

**Comment by jleni** [comment]
Yes, the problem seems to be in the usb transport library and/or chrome. Very likely a recently release chrome version triggers this issue. There have been no changes in the libraries or app. Nevertheless, we are talking to Ledger to understand if they've seen this issue already in the field.

**Comment by razimih** [comment]
same here (chrome Version 87.0.4280.66 (Official Build) (64-bit)). Started about 2 days ago. Edge doesn't seem to work either...

**Comment by jleni** [comment]
as described here, it seems related to a chrome upgrade: https://github.com/polkadot-js/apps/issues/4049#issuecomment-731045937

> If you are affected, would suggest going to chrome://flags#new-usb-backend and disabling it and seeing it is improves.
