### ISSUE TITLE
Error: bad signature on polkadot.js

### ISSUE THREAD

**Issue by anjaw3f** [Zondax/ledger-kusama#56]
A few users are reporting the error "1010: Invalid Transaction: Transaction has a bad signature" when trying to send KSM/DOT from their Ledger on polkadot.js

This happens for both Kusama and Polkadot.

Jaco: "That gets returned from the Node itself - it means that the signature that is generated by the Ledger for the transaction payload is not recognizable by the RPC node."

Can you help?

https://github.com/polkadot-js/apps/issues/4487

**Comment by jleni** [comment]
Thanks Anja,
Could you provide more context information? 
- What specific transaction was being signed?
- Any specific version?
- Since when you've been receiving these errors? Given that the apps have not changed, it would be important to know if this could be associated to some recent upgrade in the runtime.

**Comment by anjaw3f** [comment]
It just started suddenly happening over the weekend. I've had three cases in a row. Have asked users for more info and will report back here or ask them to comment directly.

**Comment by anjaw3f** [comment]
More context has been added to the original thread here: polkadot-js/apps#4487

**Comment by elfif** [comment]
Hello, i'm upping this up. There has been quite some talk on [polkadot-js/apps#4487](https://github.com/polkadot-js/apps/issues/4487) but nothing recently. Last post suggested solution will come from the ledger apps itself. 
Any news or ETA ?

**Comment by elfif** [comment]
Hello again

No news or progress on that thing for the last week or so.
It's really deceiving. I feel like neither team between Zondax and polkadot-js wants to step up.

In the end it might just prove that polkadot governance is weak and inexistant. You do not keep some iuser assets frozen like that. I agree solution might be complicated to implement. 

But the fact that it looks like there is no pilot on the plane is bad....

**Comment by jleni** [comment]
Hi, this is not the case. We've been definitely working hard on this.
We need to be careful with what we are doing. The code is ready and we are talking to Ledger to streamline the review process.

[https://github.com/Zondax/ledger-kusama/pull/64](https://github.com/Zondax/ledger-kusama/pull/64

PLEASE DO NOT USE YET. We are working on some detailed instructions once the app is published to mitigate any other user mistakes.

**Comment by MagnatUK** [comment]
Any update on the fix?

**Comment by feelwelltm** [comment]
I have reinstalled the new kusama version 4.28.2  on my nano ledger s.
I have the same 1010 error with my ledger when i want to transfer the Kusama from the Polkadot wallet!  on the  https://polkadot.js.org/apps 
i cant send the kusama anywhere!!!!! please help and make a version of Kusama that works!!! I have ledger for security not for problems ok...be serious

**Comment by elfif** [comment]
Hello there. 
I successfully installed the kusama_sec app.
@feelwelltm @daledenton1 , you need to enable "Developer mode" in settings => experimental feature of ledger live.
Then you will see the app.

Nevertheless, issue remains on my side.
I went to polkadot-js and i follow those steps:

- Switched to on the "only for this network" radiobox on my polkadot account that is managed by my Ledger
- Went to Kusama network and removed all accounts, just in case.
- Launch the kusama_sec on my ledger
- Import account from my Ledger

And then yes an account appeared, but it's empty. **My KSM are not there**.
This app generated yet another account with another public address.
But it's still not the good one.

I have no idea how this thing got tested or even if there is only one potential issue regarding interactions between polkadot-js and Ledger.........

**Comment by UltimateInvestor** [comment]
I can't transfer out of my ledger nano x. I just deposited into my KSM account but I can't move it out of it anymore. Gives me error message,

balances.transferKeepAlive
Spec version not supported

Please help me access my money!

**Comment by daledenton1** [comment]
Welcome to the club @UltimateInvestor! I haven't been able to do a thing with my $KSM and $DOT funds since I transferred them to my Polkadot.js wallet. Every time there is an update they say it should be fixed with a couple days, well that was weeks ago and we are still waiting! We are really all getting left in the dark here. I'm thinking I can kiss my $60k goodbye!!

**Comment by UltimateInvestor** [comment]
Oh I forgot to respond. It's fixed. Need to update your DOT and KSM firmware and it should work.

**Comment by jleni** [comment]
Hello everyone,
 
The KSM and the DOT Recovery Modes are operational (on ledger devices). This recovery mode allows you to unblock and recover KSM that got accidentally sent to Polkadot addresses, and vice versa (retrieve DOT that got accidentally sent to a Kusama address).

**DOT Recovery Mode**:

* [Written instructions](https://medium.com/zondax/how-to-recover-dot-sent-to-the-wrong-network-kusama-2f89b5d0b93d)
* [Video tutorial](https://www.youtube.com/watch?v=qJPwguvRz80)
 
 **KSM Recovery Mode**:
 
* [Written instructions ](https://medium.com/zondax/how-to-recover-ksm-sent-to-the-wrong-network-polkadot-f8865fa094a0)
* [Video Tutorial ](https://www.youtube.com/watch?v=hM0ApWzEzeA&feature=emb_title)
