### ISSUE TITLE
Kusama not showing on MathWallet 

### ISSUE THREAD

**Issue by dllhg** [Zondax/ledger-kusama#70]
I just sent half my KSM balance from binance over to this new MathWallet I downloaded on my iOS   

It shows the transaction on the wallet but shows zero balance.

Appreciate any help people can give. 

Thanks.

**Comment by jleni** [comment]
Unfortunately we are not related in any way to MathWallet.

I would suggest contacting MathWallet and/or Binance about this

Maybe you can also write to support@polkadot.network
