### ISSUE TITLE
 Ledger error: App "kusama" does not seem to be open

### ISSUE THREAD

**Issue by abufarj919** [Zondax/ledger-kusama#71]
I have updated new kusama version 4.28.2 and kusama app still will not stay open in ledger so in turn unable to sign transaction. " Ledger error: App "kusama" does not seem to be open

**Comment by EvilBlueBoo** [comment]
Using the Kusama_sec app I get this:
![image](https://user-images.githubusercontent.com/72707582/107858827-d6a09880-6dfb-11eb-9108-19e341918170.png)

I was trying to send from this:
![image](https://user-images.githubusercontent.com/72707582/107858840-e91ad200-6dfb-11eb-9e6d-56c70bc6e6ba.png)
(DOT derived Ledger acct on Kusama)

**Comment by abufarj919** [comment]
issue resolved

**Comment by jleni** [comment]
`Kusama_sec` SHOULD NOT BE USED. 

It is actually a very technical app used by only a few specific users.

We will discuss with Ledger removing this app from their standard app store if possible.
