### ISSUE TITLE
My Ledger is stuck on "loading" 

### ISSUE THREAD

**Issue by MIHAI-CFM** [Zondax/ledger-kusama#72]
I have a problem with the ledger connection. When I want to create a new account attached to the ledger wallet I get stuck in loading. 
I tried to reset the application but in vain. Since 15.02.2021 I keep trying but to no avail.
I noticed that this problem was also in January, do you think it will be solved. Below I leave the link where I read about the problem. Thank you!

https://support.polkadot.network/support/solutions/articles/65000173833-my-ledger-is-stuck-on-loading-on-polkadot-js

**Comment by Nadiaaa17** [comment]
i also have the same problem since 18/02, the support help you ?  
![screeshot apply polkadot](https://user-images.githubusercontent.com/79416905/108633784-78685b00-7476-11eb-946c-c067ab7411eb.PNG)

**Comment by MIHAI-CFM** [comment]
Yes, the operating system was the cause for me. I was using Windows 7,
it worked on Windows 10. I hope it helps.


dum., 21 feb. 2021, 19:56 Nadiaaa17 <notifications@github.com> a scris:

**Comment by jleni** [comment]
Unfortunately, the issues you are describing are not related to our deliverables (Ledger app) but to polkadot.js and Ledger drivers.

Also as @MIHAI-CFM indicated, Windows 7 is not supported by Ledger's drivers. I have just opened an issue so users are informed about this restriction
