### ISSUE TITLE
Cannot do session.setKeys on Nano S

### ISSUE THREAD

**Issue by nicolasochem** [Zondax/ledger-kusama#74]
On Kusama, using session.setKeys with Ledger Nano X official app v4.28.3 works fine, however I saw that the session key was truncated on the screen. It was only showing me 5 screens of data, then "approve/deny". The signature included the entire key, however.

But with Ledger Nano S, the following happens:

I get 8 screens of data. Session key is trucated.

Then I click right and I get "ERROR SHOWING DATA"

Then I click right again (v symbol for "approve") and my polkadot.js app crashes.

I have opened an issue on polkadot js app as well, but it looks like it's an issue with the app since it works on X:

https://github.com/polkadot-js/apps/issues/5086

**Comment by nicolasochem** [comment]
It may be a duplicate of #68, but it looks like it's only happening on S. X works fine.
@vekexasia could you confirm you were using a Nano S?

I also opened a different ticket for truncated session key.

**Comment by l30c0d35** [comment]
same here! Can't sign the set session keys transaction on my ledger nano s, the app seems to crash once I click through the review of the tx hash

This should really not be happening! Can you give an estimate on how long you will need to fix this error?

**Comment by jleni** [comment]
related to https://github.com/LedgerHQ/app-kusama/pull/9

**Comment by l30c0d35** [comment]
Could we get an update on the progress? How much longer do you estimate this is going to take? Is just a new update from your side required or will we need to wait for ledger as well?

**Comment by jleni** [comment]
it requires this PR to be merged and released https://github.com/LedgerHQ/app-kusama/pull/9

We will ping Ledger again about this

**Comment by l30c0d35** [comment]
that'd be great

**Comment by nicolasochem** [comment]
This was an issue before runtime upgrade so unless you fixed it specifically it will still be present in the new version.

**Comment by l30c0d35** [comment]
is it save to switch from the regular Kusama app to the XL version? Will the accounts migrate or is there a manual action required or is it not possible at all to migrate the accounts? [LedgerHQ#9](https://github.com/LedgerHQ/app-kusama/pull/9) @jleni

**Comment by jleni** [comment]
This should be possible since the last PR.

https://github.com/Zondax/ledger-kusama#session

**Comment by lucamarrocco** [comment]
Hello, I have this exact problem now. Ledger Nano, Kusama (KSM) app v5.30.1

**Comment by nicolasochem** [comment]
@emmanuelm41 @jleni I think this one is still crashing, it may have been closed incorrectly. I hope to try again in a week or so, but could you please check?

**Comment by emmanuelm41** [comment]
@nicolasochem I added a test [here](https://github.com/Zondax/ledger-kusama/pull/93) to check setKeys tx and it works well.  Did you test the app again and it is still crashing?

**Comment by nicolasochem** [comment]
@emmanuelm41 I have not had a chance to try, can you try with real HW? I stronly suspect it is still a problem. Can you reopen the issue?

**Comment by emmanuelm41** [comment]
@nicolasochem, I tested that type of tx (SetKeys) with real HW, and it seems to work (using the version you can compile here https://github.com/Zondax/ledger-kusama/pull/93. Could you test it too?

**Comment by nicolasochem** [comment]
Thanks Emmanuel, did you try with Nano S?

**Comment by emmanuelm41** [comment]
> Thanks Emmanuel, did you try with Nano S?
> […](#)

Yes, I did it! I used a ledger Nano S. Please, try it yourself and let me know.

**Comment by nicolasochem** [comment]
I tried with the most recent release from Ledger live and it's still broken. Are you pushing this new version to Ledger Live soon?

**Comment by emmanuelm41** [comment]
I am not sure when we are going to release a new version, but you should test it with the correct app you can compile with dev branch. If you can't do it now, please wait until we release a new version! @jleni do you have any idea about it?

**Comment by nicolasochem** [comment]
I can't do it with a dev version. Please reopen the ticket until there is a
new release.

**Comment by ainhoa-a** [comment]
New release of kusama published https://github.com/LedgerHQ/app-kusama/releases/tag/v9.9160.1
