### ISSUE TITLE
session key truncated on ledger screen

### ISSUE THREAD

**Issue by nicolasochem** [Zondax/ledger-kusama#75]
Using session.setKeys extrinsic, I only see 5 screens of key on Nano X and 8 screen of keys on Nano S. It's not enough to verify the entire key, especially the last characters. But signature is correct, it's just a display issue.

**Comment by emmanuelm41** [comment]
Hi @nicolasochem, could you give me some example data to test? I added a new test to check that, and it passed.

**Comment by emmanuelm41** [comment]
@nicolasochem could you give me some example data to test it? I added a new test to check but it passed with no errors.
