### ISSUE TITLE
Kusama app in Ledger Nano S shows only one account  Added via  Ledger in Polkadot.js apps

### ISSUE THREAD

**Issue by goranad77** [Zondax/ledger-kusama#77]
Hi I added via Ledger one account in Polkadot.js apps and used it. The problem appeared when I added the second account.  Since then when I try on the first account Show address on hardware device the Kusama app shows me the address of the second account . When I try to transfer funds from the first account to injected one Ledger shows me the address of the second account and I can not make transfer (error 1010). I "forget" the second account and nothing has changed. Ledger shows the address of the second account. 
This might be helpful to the developers:
The first account on Polkadot.js apps was created by add via  Ledger  on Polkadot network by using option Allow on all networks so I got account on Kusama network either.  I used both Polkadot and Kusama accounts on Ledger Nano S but not at the same time because of the lack of memory and had no problem. Now I can install Polkdot app and use Polkadot account but when I install Kusama app can not use the Kusama account.
The second account was created and added via Ledger on Kusama network directly.
Is it possible that account added on Kusama netowork directly, somehow has priority?
Do not let this question of mine mislead  you.
Anyway, I am in situation that I can not approach to my funded account and it is chaos that I did not expect.
Kusama v. 4.28.3 right now on my Ledger. The first account was created and used in march the second a week ago and I
I am not the developer. I hope I explain the situation well.  If you have any question I will try to answer. My account is funded and I expect the solution.

**Comment by goranad77** [comment]
Any news regarding the issue I had reported? I can not connect Polkadot.js apps account and Ledger properly. Kusama app shows me wrong address.

**Comment by jleni** [comment]
Thanks for your message. 
The problem you are describing is related to polkadot.js (webwallet) not the software running in the device itself.
We would recommend opening this issue in their repository https://github.com/polkadot-js/apps
