### ISSUE TITLE
Kusama ledger app not working at all after protocol upgrade to 2030

### ISSUE THREAD

**Issue by nicolasochem** [Zondax/ledger-kusama#78]
Hi, it seems that all Ledger transactions are failing since the last protocol upgrade yesterday.

There is an issue open on polkadot js app as well:

https://github.com/polkadot-js/apps/issues/5089

Issue says "transaction version not supported".

**Comment by jleni** [comment]
related to https://github.com/LedgerHQ/app-kusama/pulls

**Comment by tededi** [comment]
who's working on the fix and when will it be finished ?

**Comment by Rhulain** [comment]
I am also getting this problem, "txn version not supported"

**Comment by tededi** [comment]
how long until its fixe? this is not good enough

**Comment by peter1401maier** [comment]
I am also getting this problem, "txn version not supported" - please fix this!!!!

**Comment by Rhulain** [comment]
> Probably looking at a week until its done. Theres been no communication from ledger and i can't find anyone to speak to.

Thanks for checking. I don't think the update should have been released until Ledger had the new app ready.

**Comment by tededi** [comment]
100% this should never happen. We are basically locked out of our accounts.

**Comment by peter1401maier** [comment]
> 100% this should never happen. We are basically locked out of our accounts.

What? That would be a mega disaster!
Is that reliable information?
