### ISSUE TITLE
cannot do staking.setController() on Nano S with new version of Kusama app

### ISSUE THREAD

**Issue by nicolasochem** [Zondax/ledger-kusama#79]
I get the error: 
![image (9)](https://user-images.githubusercontent.com/93067/115779251-99610580-a36c-11eb-887f-9f9bd9f2c13d.png)

This used to work before runtime upgrade.

I also saw that the new version 5.30.0 of Kusama app is only 44kb while the previous version was much bigger. This is maybe speculation but I suspect that this release is not the equivalent of the ["XL" version of the polkadot app](https://support.ledger.com/hc/en-us/articles/360016289919-Polkadot-DOT-), but the "lite" version which does not support all operations, and the XL version still has to be developed. @jleni could you please comment?

**Comment by jleni** [comment]
This is correct.. all our substrate apps now can be compiled and deploy in both modes
We will check with Ledger if/when they can release an XL version of Kusama too. The code supports that.

**Comment by nicolasochem** [comment]
I don't see a XL version of Kusama app on Ledger today. Can we please reopen until it's released?

**Comment by l30c0d35** [comment]
I don't understand where to download the XL version either, shouldn't there be two separate download version (xl and lite)? Can someone please advise where you can revert to the XL version.

**Comment by jleni** [comment]
requires this PR to be merged and released https://github.com/LedgerHQ/app-kusama/pull/9
