### ISSUE TITLE
Cannot undo stash and controller pair (Ledger Nano S)

### ISSUE THREAD

**Issue by l30c0d35** [Zondax/ledger-kusama#81]
I have created a stash and a controller wallet with Ledger Nano S and the Polkadot-ui-js. Setting session keys with Ledger Nano S does not work with the latest version #74, hence I tried to set a new non-ledger controller to set the session keys however setController is also an unsupported txn version #79 (why is it closed, txn version does not work). So there is no way to undo associating the stash and controller nor to set the session key. Any advice?

Ledger Nano S 
v5.30.0

**Comment by jleni** [comment]
requires this PR to be merged and released https://github.com/LedgerHQ/app-kusama/pull/9

**Comment by nicolasochem** [comment]
@jleni thanks, the new Kusama XL version supports setController, so this ticket can be closed. I haven't checked #74 but I think it's a different problem than runtime version.

The same upgrade will happen to polkadot soon, please make sure the new versions are rolled out when it happens.

**Comment by jleni** [comment]
AFAIK polkadot upgrades have been merged and deployed already
