### ISSUE TITLE
proxy.addProxy(delegate, proxy_type, delay) not supported

### ISSUE THREAD

**Issue by l30c0d35** [Zondax/ledger-kusama#82]
Creating a proxy account for ledger-managed Kusama account is not supported. (`proxy.addProxy(delegate, proxy_type, delay)`)
Was that supported in the XL version before?
Are you planning to include this in future versions?
Is this because of the latest runtime upgrade and related to #79?

using:
Ledger Nano S
v5.30.0

**Comment by jleni** [comment]
Depends on https://github.com/LedgerHQ/app-kusama/pull/9

**Comment by jleni** [comment]
this is all available in the latest version
https://github.com/Zondax/ledger-kusama#proxy
