### ISSUE TITLE
Status of batch transactions on Kusama Ledger app

### ISSUE THREAD

**Issue by vikiival** [Zondax/ledger-kusama#83]
I would like to add support for [Ledger on KodaDot](https://github.com/kodadot/nft-gallery/issues/218), however, `batch` transactions don't work on this HW wallet. 

[The previous effort via extension was denied](https://github.com/polkadot-js/extension/issues/688)

So my question is what's the status of the batch transactions on Kusama/Polkadot ?

**Comment by jleni** [comment]
this should be available in the latest version
https://github.com/Zondax/ledger-kusama#utility

**Comment by vikiival** [comment]
@jleni it still does not work :/

<img width="545" alt="Screenshot 2021-07-13 at 11 02 34" src="https://user-images.githubusercontent.com/22471030/125424326-4138db34-10a3-42eb-a756-363a7cbfc1c9.png">
<img width="536" alt="Screenshot 2021-07-13 at 11 03 33" src="https://user-images.githubusercontent.com/22471030/125424350-18e49a1b-97de-4a0a-b1b0-2cc97b887a24.png">

**Comment by vikiival** [comment]
I'm using the latest version v5.30.1

**Comment by jleni** [comment]
The support was added several weeks ago but Ledger has not published the update yet.

As you can see, this will appear in versions > 5.9040 and upwards
https://github.com/Zondax/ledger-kusama#kusama--59040x

**Comment by prastut** [comment]
Hey @jleni do you have awareness on when Ledger will publish this update? 
Or people/community I should reach out to check for an update on this?
