### ISSUE TITLE
Support tips.reportAwesome

### ISSUE THREAD

**Issue by gabrieljaegerde** [Zondax/ledger-kusama#87]
Are you already working on an update to the app? With kusamas new runtime update a week ago, the current one is not working...

**Comment by nndiaye-ledger** [comment]
Hello @gabrieljaegerde can you please provide more details, the latest Kusama app version is 5.30.1 to be able to update make sure that you have the latest Ledger FW version ( LNS 2.0.0 and LNX 1.3.0).

**Comment by gabrieljaegerde** [comment]
There was already a new runtime release again for kusama and polkadot. v30 is not the latest one anymore.

**Comment by nndiaye-ledger** [comment]
Can you please give us more details on the issue you are facing so that we can investigate.

**Comment by gabrieljaegerde** [comment]
When proposing a tip I get the error: tips.reportAwesome not supported when I try to sign the transaction.

**Comment by jleni** [comment]
Thanks Gabriel, if I understand well, what you are describing is a missing feature `tips.reportAwesome` that is available in the new runtime.

Runtimes are classified by the their tx version, in this case v5. This means that the current application is expected to work correctly in the current runtime.

Whenever there is a breaking change signalled by a change in this number, the upgrade is required and relatively urgent.

With respect to new pallets and features like the one you describe, we normally schedule them over time. Also we prioritize them in coordination with other stakeholders. In some cases, it is not even possible to support all of them as the app size would grow beyond the limitations of these devices.

Be sure that we will considering including this specific feature in the near term.

I will rename the issue to track this correctly.

**Comment by jleni** [comment]
This is now supported in the XL version of the app.
