### ISSUE TITLE
Support for the crowdloan module

### ISSUE THREAD

**Issue by fxgamundi** [Zondax/ledger-kusama#88]
Hi. Seeing that the [parachain auctions are coming](https://kusama.network/auctions), it would be great if the Ledger app would support the crowdloan extrinsics (mainly, contribute, addMemo), given that multiple parachains are planning on going down this route.

**Comment by avanderbergh** [comment]
Hi, seeing as the crowd loans have started, we really need support for this... @jleni , is this in the pipeline? Or do I have to move my KSM to another wallet to contribute to these first crowd loans?

**Comment by k** [comment]
Yes +1 we need this! I'm staking so I can't transfer funds to a new address for the crowdloans. Is this almost done?

**Comment by ftheirs** [comment]
Included in latest https://github.com/Zondax/ledger-kusama/releases/tag/v11.9200.1
